services:
  hhvm:
    container_name: theodore-sgml-stream-exam-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 48567:10641
